sudo: false
language: php
php:
    - 5.6
    - 7
    - hhvm
services: sqlite3
before_script:
    - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]] ; then echo yes | pecl install apcu-4.0.11; fi;
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then echo yes | pecl install apcu; fi;
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then echo yes | pecl install apcu_bc; fi;
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]] echo 'apc.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]] echo 'apc.enabled = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
    - composer self-update
    - composer install --prefer-source
script:
    - chmod -R 777 tests/logs
    - ./vendor/bin/phpunit --coverage-clover tests/logs/clover.xml
    - chmod 777 tests/logs/clover.xml
after_success:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then travis_retry php vendor/bin/coveralls; fi
